name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  GO_VERSION: '1.24'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Clean up test files
        run: rm -f test-directory.go test-api.go || true

      - name: Run tests
        run: GOWORK=off go test -v -mod=mod ./...

      - name: Run vet
        run: GOWORK=off go vet ./...

  build:
    name: Build (Linux AMD64)
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build binary
        run: |
          # Build with SQLite support
          CGO_ENABLED=1 GOWORK=off go build -mod=mod -ldflags="-s -w" -o koneksi-backup ./cmd/koneksi-backup
          
          # Verify the binary
          ./koneksi-backup --version || ./koneksi-backup help

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: koneksi-backup-linux-amd64
          path: koneksi-backup